language: node_js

stages:
  - name: release
    if: branch = master AND type != pull_request

notifications:
  email: false

jobs:
  include:
    - stage: release
      node_js: '8'
      script: npm run semantic-release
